export const FETCH_ALL_CUSTOMERS_PENDING = 'FETCH_ALL_CUSTOMERS_PENDING'
export const FETCH_ALL_CUSTOMERS_SUCCESS = 'FETCH_ALL_CUSTOMERS_SUCCESS'
export const FETCH_ALL_CUSTOMERS_FAILED = 'FETCH_ALL_CUSTOMERS_FAILED'

export const FETCH_ONE_CUSTOMER_PENDING = 'FETCH_ONE_CUSTOMER_PENDING'
export const FETCH_ONE_CUSTOMER_SUCCESS = 'FETCH_ONE_CUSTOMER_SUCCESS'
export const FETCH_ONE_CUSTOMER_FAILED = 'FETCH_ONE_CUSTOMER_FAILED'

export const REMOVE_CUSTOMER_PENDING = 'REMOVE_CUSTOMER_PENDING'
export const REMOVE_CUSTOMER_SUCCESS = 'REMOVE_CUSTOMER_SUCCESS'
export const REMOVE_CUSTOMER_FAILED = 'REMOVE_CUSTOMER_FAILED'

export const ADD_NEW_CUSTOMER_PENDING = 'ADD_NEW_CUSTOMER_PENDING'
export const ADD_NEW_CUSTOMER_SUCCESS = 'ADD_NEW_CUSTOMER_SUCCESS'
export const ADD_NEW_CUSTOMER_FAILED = 'ADD_NEW_CUSTOMER_FAILED'

export const EDIT_ONE_CUSTOMER_PENDING = 'EDIT_ONE_CUSTOMER_PENDING'
export const EDIT_ONE_CUSTOMER_SUCCESS = 'EDIT_ONE_CUSTOMER_SUCCESS'
export const EDIT_ONE_CUSTOMER_FAILED = 'EDIT_ONE_CUSTOMER_FAILED'



