export const FETCH_ALL_CUSTOMERS_PENDING = 'FETCH_ALL_CUSTOMERS_PENDING'
export const FETCH_ALL_CUSTOMERS_SUCCESS = 'FETCH_ALL_CUSTOMERS_SUCCESS'
export const FETCH_ALL_CUSTOMERS_FAILED = 'FETCH_ALL_CUSTOMERS_FAILED'