export const FETCH_ALL_CUSTOMERS_PENDING = 'FETCH_ALL_CUSTOMERS_PENDING'
export const FETCH_ALL_CUSTOMERS_SUCCESS = 'FETCH_ALL_CUSTOMERS_SUCCESS'
export const FETCH_ALL_CUSTOMERS_FAILED = 'FETCH_ALL_CUSTOMERS_FAILED'

export const FETCH_ONE_CUSTOMERS_PENDING = 'FETCH_ONE_CUSTOMERS_PENDING'
export const FETCH_ONE_CUSTOMERS_SUCCESS = 'FETCH_ONE_CUSTOMERS_SUCCESS'
export const FETCH_ONE_CUSTOMERS_FAILED = 'FETCH_ONE_CUSTOMERS_FAILED'

export const REMOVE_CUSTOMERS_PENDING = 'REMOVE_CUSTOMERS_PENDING'
export const REMOVE_CUSTOMERS_SUCCESS = 'REMOVE_CUSTOMERS_SUCCESS'
export const REMOVE_CUSTOMERS_FAILED = 'REMOVE_CUSTOMERS_FAILED'

export const ADD_NEW_CUSTOMERS_PENDING = 'ADD_NEW_CUSTOMERS_PENDING'
export const ADD_NEW_CUSTOMERS_SUCCESS = 'ADD_NEW_CUSTOMERS_SUCCESS'
export const ADD_NEW_CUSTOMERS_FAILED = 'ADD_NEW_CUSTOMERS_FAILED'

export const EDIT_ONE_CUSTOMERS_PENDING = 'EDIT_ONE_CUSTOMERS_PENDING'
export const EDIT_ONE_CUSTOMERS_SUCCESS = 'EDIT_ONE_CUSTOMERS_SUCCESS'
export const EDIT_ONE_CUSTOMERS_FAILED = 'EDIT_ONE_CUSTOMERS_FAILED'



